name: Build & upload to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "android/app/google_service.json"
          FILE_DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "lib/firebase_options.dart"
          FILE_DATA: ${{secrets.FIREBASE_OPTION}}

      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APPID}}
            token: ${{secrets.TOKEN}}
            groups: pre_tester
            file: build/app/outputs/apk/release/app-release.apk
